POST http://localhost:3333/users
Content-Type: application/json

{
    //is not accepted empty body
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Erick",
    "username": "Erick8080"
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Diego",
    "username": "DiegoLeon800"
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "André",
    "username": "AndreiBR"
}