POST http://localhost:3333/todos
Content-Type: application/json
username: AndreiBR

{
    //is not accepted empty body
}

###

POST http://localhost:3333/todos
Content-Type: application/json
username: DiegoLeon800

{
    "title" : "Limpar a cozinha",
    "deadline": "2021-05-20"
}

###

POST http://localhost:3333/todos
Content-Type: application/json
username: Erick8080

{
    "title" : "Lavar a louça",
    "deadline": "2021-06-20"
}